apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: custom-error-pages
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  project: urfu-link
  source:
    repoURL: https://github.com/ConquestSucks/urfu-link.git
    targetRevision: master
    path: deploy/k8s/platform/ingress/custom-errors
  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-nginx
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
