apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  project: urfu-link
  source:
    repoURL: https://charts.external-secrets.io
    targetRevision: 2.2.0
    chart: external-secrets
    helm:
      releaseName: external-secrets
      parameters:
        - name: installCRDs
          value: "true"
  ignoreDifferences:
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      managedFieldsManagers:
        - external-secrets
        - Go-http-client
      jqPathExpressions:
        - .spec
        - .metadata.annotations
        - .metadata.labels
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
