apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-4"
spec:
  project: urfu-link
  source:
    repoURL: https://kubernetes.github.io/ingress-nginx
    targetRevision: 4.12.0
    chart: ingress-nginx
    helm:
      releaseName: ingress-nginx
      parameters:
        - name: controller.admissionWebhooks.certManager.enabled
          value: "true"
        - name: controller.hostNetwork
          value: "true"
        - name: controller.dnsPolicy
          value: ClusterFirstWithHostNet
        - name: controller.service.type
          value: ClusterIP
        - name: controller.kind
          value: DaemonSet
      values: |
        controller:
          config:
            server-snippet: |
              location = /.pomerium/sign_in {
                proxy_pass http://pomerium.urfu-platform.svc.cluster.local:80;
                proxy_set_header Host auth.ghjc.ru;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
              }

  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-nginx
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
