apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom
  namespace: kube-system
data:
  id.ghjc.ru.override: |
    rewrite name id.ghjc.ru ingress-nginx-controller.ingress-nginx.svc.cluster.local
