apiVersion: kafka.strimzi.io/v1
kind: Kafka
metadata:
  name: urfu-kafka
  namespace: urfu-platform
  annotations:
    strimzi.io/node-pools: enabled
    strimzi.io/kraft: enabled
spec:
  kafka:
    version: 3.9.0
    listeners:
      - name: internal
        port: 9092
        type: internal
        tls: false
  entityOperator:
    topicOperator: {}
    userOperator: {}
