apiVersion: kafka.strimzi.io/v1
kind: KafkaNodePool
metadata:
  name: kafka-broker
  namespace: urfu-platform
  labels:
    strimzi.io/cluster: urfu-kafka
spec:
  replicas: 1
  roles:
    - broker
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: 2000m
      memory: 2Gi
  storage:
    type: jbod
    volumes:
      - id: 0
        type: persistent-claim
        size: 200Gi
        class: fast-ssd
        deleteClaim: false
