apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - storageclass-fast-ssd.yaml
  - postgres-cluster.yaml
  - postgres-scheduled-backup.yaml
  - mongodb-cluster.yaml
  - mongodb-backup-cronjob.yaml
  - redis-cluster.yaml
  - redis-backup-cronjob.yaml
  - platform-bootstrap-job.yaml
  - minio-bootstrap-job.yaml
  - minio-tenant.yaml
  - minio-buckets-job.yaml
  - kafka-cluster.yaml
  - kafka-mixed-pool.yaml
  - kafka-topics.yaml
