apiVersion: minio.min.io/v2
kind: Tenant
metadata:
  name: urfu-minio
  namespace: urfu-platform
spec:
  image: quay.io/minio/minio:RELEASE.2025-01-20T14-49-07Z
  configuration:
    name: urfu-minio-env-config
  pools:
    - name: pool-0
      servers: 1
      volumesPerServer: 1
      volumeClaimTemplate:
        metadata:
          name: data
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 50Gi
          storageClassName: fast-ssd
      resources:
        requests:
          memory: 1Gi
          cpu: 500m
        limits:
          memory: 2Gi
          cpu: 2000m
  mountPath: /export
  requestAutoCert: true
  features:
    bucketDNS: false
