apiVersion: batch/v1
kind: Job
metadata:
  name: minio-bootstrap-buckets
  namespace: urfu-platform
  annotations:
    argocd.argoproj.io/sync-options: Force=true,Replace=true
    argocd.argoproj.io/sync-wave: "1"
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: mc
          image: minio/mc:RELEASE.2025-08-13T08-35-41Z
          command:
            - /bin/sh
            - -c
            - >-
              until [ -s /bootstrap/endpoint ] && [ -s /bootstrap/access_key ] && [ -s /bootstrap/secret_key ]; do sleep 5; done &&
              MINIO_ENDPOINT="$(cat /bootstrap/endpoint)" &&
              MINIO_ACCESS_KEY="$(cat /bootstrap/access_key)" &&
              MINIO_SECRET_KEY="$(cat /bootstrap/secret_key)" &&
              until mc alias set minio "$MINIO_ENDPOINT" "$MINIO_ACCESS_KEY" "$MINIO_SECRET_KEY"; do sleep 5; done &&
              mc mb -p minio/media-private || true &&
              mc mb -p minio/media-public || true &&
              mc anonymous set download minio/media-public &&
              mc mb -p minio/user-avatars || true &&
              mc anonymous set download minio/user-avatars
          volumeMounts:
            - name: bootstrap-secret
              mountPath: /bootstrap
              readOnly: true
      volumes:
        - name: bootstrap-secret
          secret:
            secretName: minio-bootstrap-secret
            optional: true
