apiVersion: v1
kind: Secret
metadata:
  name: mongo-app-user-password
  namespace: urfu-platform
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
type: Opaque
stringData:
  password: "PLACEHOLDER_WILL_BE_REPLACED_BY_BOOTSTRAP"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mongodb-database
  namespace: urfu-platform
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
---
apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: urfu-mongo
  namespace: urfu-platform
spec:
  members: 1
  type: ReplicaSet
  version: "8.0.5"
  security:
    authentication:
      modes: ["SCRAM"]
    tls:
      enabled: false
  users:
    - name: app-user
      db: admin
      passwordSecretRef:
        name: mongo-app-user-password
      roles:
        - name: readWrite
          db: chat_db
        - name: readWrite
          db: call_db
        - name: readWrite
          db: presence_db
      scramCredentialsSecretName: app-user-scram
  statefulSet:
    spec:
      template:
        spec:
          containers:
            - name: mongod
              resources:
                requests:
                  cpu: 100m
                  memory: 256Mi
                limits:
                  cpu: 500m
                  memory: 1Gi
            - name: mongodb-agent
              resources:
                requests:
                  cpu: 50m
                  memory: 64Mi
                limits:
                  cpu: 250m
                  memory: 256Mi
          initContainers:
            - name: mongod-posthook
              resources:
                requests:
                  cpu: 50m
                  memory: 64Mi
                limits:
                  cpu: 250m
                  memory: 256Mi
            - name: mongodb-agent-readinessprobe
              resources:
                requests:
                  cpu: 50m
                  memory: 64Mi
                limits:
                  cpu: 250m
                  memory: 256Mi
      volumeClaimTemplates:
        - metadata:
            name: data-volume
          spec:
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 100Gi
            storageClassName: fast-ssd
