apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mongo-app-user-password
  namespace: urfu-platform
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: mongo-app-user-password
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: urfu-link/prod/mongo
        property: app_user_password
