apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: urfu-postgres-nightly
  namespace: urfu-platform
spec:
  schedule: "0 2 * * *"
  cluster:
    name: urfu-postgres
  immediate: true
  backupOwnerReference: self
  method: barmanObjectStore
