nameOverride: presence-service
fullnameOverride: presence-service
image:
  repository: urfu-link/presence-service
  pullPolicy: IfNotPresent
  tag: dev-local

replicaCount: 1

env:
  ASPNETCORE_ENVIRONMENT: Development
  ASPNETCORE_URLS: http://+:8080

secrets:
  enabled: true
  name: presence-service-secrets

rollout:
  enabled: false
  autoPromotionEnabled: true

autoscaling:
  enabled: false

serviceMonitor:
  enabled: false

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 256Mi

