nameOverride: presence-service
fullnameOverride: presence-service
image:
  repository: ghcr.io/conquestsucks/urfu-link/presence-service
  pullPolicy: IfNotPresent
  tag: sha-c872136

imagePullSecrets:
  - name: ghcr-pull-secret

replicaCount: 1

env:
  ASPNETCORE_ENVIRONMENT: Production
  ASPNETCORE_URLS: http://+:8080
  Observability__Otlp__Endpoint: http://otel-collector.observability.svc.cluster.local:4317
  Kafka__BootstrapServers: urfu-kafka.urfu-platform.svc.cluster.local:9092
  Auth__Authority: http://keycloak.urfu-platform.svc.cluster.local:8080/realms/urfu-link
  Auth__MetadataAddress: http://keycloak.urfu-platform.svc.cluster.local:8080/realms/urfu-link/.well-known/openid-configuration
  Auth__ValidIssuer: https://id.ghjc.ru/realms/urfu-link
  Infrastructure__Redis__Configuration: urfu-redis.urfu-platform.svc.cluster.local:6379

secrets:
  enabled: true
  name: presence-service-secrets

rollout:
  enabled: true
  autoPromotionEnabled: true

autoscaling:
  enabled: false

serviceMonitor:
  enabled: true

resources:
  requests:
    cpu: 25m
    memory: 64Mi
  limits:
    cpu: 250m
    memory: 256Mi
