// <auto-generated />
using MediaService.Api.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace MediaService.Api.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(MediaDbContext))]
    [Migration("20260531030000_AddMediaAssetDurationSeconds")]
    partial class AddMediaAssetDurationSeconds
    {
    }
}
