apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-admin
  namespace: observability
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: grafana-admin
    template:
      data:
        admin-user: admin
        admin-password: "{{ .admin_password }}"
  data:
    - secretKey: admin_password
      remoteRef:
        key: urfu-link/prod/grafana
        property: admin_password
