// <auto-generated />
using System;
using DisciplineService.Api.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DisciplineService.Api.Migrations
{
    [DbContext(typeof(DisciplineDbContext))]
    [Migration("20260426085356_InitialDiscipline")]
    partial class InitialDiscipline
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("disciplines")
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DisciplineService.Api.Domain.Aggregates.Discipline", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ArchivedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("archived_at_utc");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("code");

                    b.Property<Guid?>("CoverAssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("cover_asset_id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Guid>("OwnerTeacherId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_teacher_id");

                    b.Property<string>("Semester")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("semester");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("ArchivedAtUtc")
                        .HasFilter("archived_at_utc IS NULL");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("OwnerTeacherId");

                    b.HasIndex("Semester");

                    b.ToTable("disciplines", "disciplines");
                });

            modelBuilder.Entity("DisciplineService.Api.Domain.Aggregates.Enrollment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("DisciplineId")
                        .HasColumnType("uuid")
                        .HasColumnName("discipline_id");

                    b.Property<DateTimeOffset>("EnrolledAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("enrolled_at_utc");

                    b.Property<Guid>("EnrolledBy")
                        .HasColumnType("uuid")
                        .HasColumnName("enrolled_by");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("role");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("DisciplineId", "UserId")
                        .IsUnique();

                    b.HasIndex("UserId", "Role");

                    b.ToTable("enrollments", "disciplines");
                });

            modelBuilder.Entity("DisciplineService.Api.Domain.Aggregates.Enrollment", b =>
                {
                    b.HasOne("DisciplineService.Api.Domain.Aggregates.Discipline", null)
                        .WithMany("Enrollments")
                        .HasForeignKey("DisciplineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DisciplineService.Api.Domain.Aggregates.Discipline", b =>
                {
                    b.Navigation("Enrollments");
                });
#pragma warning restore 612, 618
        }
    }
}
