apiVersion: v1
kind: Namespace
metadata:
  name: urfu-platform
---
apiVersion: v1
kind: Namespace
metadata:
  name: urfu-prod
  labels:
    linkerd.io/inject: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: argocd
---
apiVersion: v1
kind: Namespace
metadata:
  name: observability
  labels:
    linkerd.io/inject: enabled
