apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: api-gateway-secrets
  namespace: urfu-prod
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: api-gateway-secrets
    creationPolicy: Owner
  data:
    - secretKey: Auth__ClientSecret
      remoteRef:
        key: urfu-link/prod/api-gateway
        property: auth_client_secret
