apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: vault-backend
spec:
  provider:
    vault:
      server: https://vault.ghjc.ru
      path: kv
      version: v2
      auth:
        kubernetes:
          mountPath: kubernetes
          role: urfu-link-prod
          serviceAccountRef:
            name: external-secrets
            namespace: external-secrets
