apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: frontend-web-oauth2
  namespace: urfu-prod
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: frontend-web-oauth2
  data:
    - secretKey: client-id
      remoteRef:
        key: urfu-link/prod/frontend-web-oauth2
        property: client_id
    - secretKey: client-secret
      remoteRef:
        key: urfu-link/prod/frontend-web-oauth2
        property: client_secret
    - secretKey: cookie-secret
      remoteRef:
        key: urfu-link/prod/frontend-web-oauth2
        property: cookie_secret
