apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mongo-backup-secret
  namespace: urfu-platform
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: mongo-backup-secret
    creationPolicy: Owner
  data:
    - secretKey: mongo_uri
      remoteRef:
        key: urfu-link/prod/mongo-backup
        property: mongo_uri
    - secretKey: minio_endpoint
      remoteRef:
        key: urfu-link/prod/mongo-backup
        property: minio_endpoint
    - secretKey: minio_access_key
      remoteRef:
        key: urfu-link/prod/mongo-backup
        property: minio_access_key
    - secretKey: minio_secret_key
      remoteRef:
        key: urfu-link/prod/mongo-backup
        property: minio_secret_key
