apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pomerium
  namespace: urfu-platform
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: pomerium
  data:
    - secretKey: client-id
      remoteRef:
        key: urfu-link/prod/pomerium
        property: client_id
    - secretKey: client-secret
      remoteRef:
        key: urfu-link/prod/pomerium
        property: client_secret
    - secretKey: cookie-secret
      remoteRef:
        key: urfu-link/prod/pomerium
        property: cookie_secret
    - secretKey: shared-secret
      remoteRef:
        key: urfu-link/prod/pomerium
        property: shared_secret
    - secretKey: signing-key
      remoteRef:
        key: urfu-link/prod/pomerium
        property: signing_key
    - secretKey: databroker-connection-string
      remoteRef:
        key: urfu-link/prod/pomerium-db
        property: connection_string
