apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: media-service-secrets
  namespace: urfu-prod
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: media-service-secrets
  data:
    - secretKey: ConnectionStrings__Primary
      remoteRef:
        key: urfu-link/prod/media-service
        property: primary_connection
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: user-service-secrets
  namespace: urfu-prod
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: user-service-secrets
  data:
    - secretKey: ConnectionStrings__Primary
      remoteRef:
        key: urfu-link/prod/user-service
        property: primary_connection
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: chat-service-secrets
  namespace: urfu-prod
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: chat-service-secrets
  data:
    - secretKey: ConnectionStrings__Primary
      remoteRef:
        key: urfu-link/prod/chat-service
        property: primary_connection
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: presence-service-secrets
  namespace: urfu-prod
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: presence-service-secrets
  data:
    - secretKey: ConnectionStrings__Primary
      remoteRef:
        key: urfu-link/prod/presence-service
        property: primary_connection
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: notification-service-secrets
  namespace: urfu-prod
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: notification-service-secrets
  data:
    - secretKey: Kafka__BootstrapServers
      remoteRef:
        key: urfu-link/prod/notification-service
        property: kafka_bootstrap_servers
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: call-service-secrets
  namespace: urfu-prod
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: call-service-secrets
  data:
    - secretKey: Kafka__BootstrapServers
      remoteRef:
        key: urfu-link/prod/call-service
        property: kafka_bootstrap_servers
