// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using UserService.Api.Infrastructure.Persistence;

#nullable disable

namespace UserService.Api.Migrations
{
    [DbContext(typeof(UserDbContext))]
    [Migration("20260522224930_CleanEmptyUserSearchProjection")]
    partial class CleanEmptyUserSearchProjection
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("users")
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "citext");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("UserService.Api.Domain.UserProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Notifications")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("notification_settings");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.ToTable("user_profiles", "users");
                });

            modelBuilder.Entity("UserService.Api.Domain.UserSearchProjection", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTimeOffset?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at_utc");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("citext")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .HasColumnType("citext")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .HasColumnType("citext")
                        .HasColumnName("first_name");

                    b.Property<long>("KeycloakModifiedMs")
                        .HasColumnType("bigint")
                        .HasColumnName("keycloak_modified_ms");

                    b.Property<string>("LastName")
                        .HasColumnType("citext")
                        .HasColumnName("last_name");

                    b.Property<string>("SearchText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("search_text");

                    b.Property<string>("SearchTextTranslit")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("search_text_translit");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("citext")
                        .HasColumnName("username");

                    b.HasKey("UserId");

                    b.ToTable("user_search_projection", "users");
                });

            modelBuilder.Entity("UserService.Api.Domain.UserProfile", b =>
                {
                    b.OwnsOne("UserService.Api.Domain.ValueObjects.AccountSettings", "Account", b1 =>
                        {
                            b1.Property<Guid>("UserProfileId")
                                .HasColumnType("uuid");

                            b1.Property<string>("AboutMe")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("about_me");

                            b1.Property<string>("AvatarUrl")
                                .HasColumnType("text")
                                .HasColumnName("avatar_url");

                            b1.HasKey("UserProfileId");

                            b1.ToTable("user_profiles", "users");

                            b1.WithOwner()
                                .HasForeignKey("UserProfileId");
                        });

                    b.OwnsOne("UserService.Api.Domain.ValueObjects.PrivacySettings", "Privacy", b1 =>
                        {
                            b1.Property<Guid>("UserProfileId")
                                .HasColumnType("uuid");

                            b1.Property<bool>("ShowLastVisitTime")
                                .HasColumnType("boolean")
                                .HasColumnName("show_last_visit_time");

                            b1.Property<bool>("ShowOnlineStatus")
                                .HasColumnType("boolean")
                                .HasColumnName("show_online_status");

                            b1.HasKey("UserProfileId");

                            b1.ToTable("user_profiles", "users");

                            b1.WithOwner()
                                .HasForeignKey("UserProfileId");
                        });

                    b.OwnsOne("UserService.Api.Domain.ValueObjects.SoundVideoSettings", "SoundVideo", b1 =>
                        {
                            b1.Property<Guid>("UserProfileId")
                                .HasColumnType("uuid");

                            b1.Property<string>("PlaybackDeviceId")
                                .HasColumnType("text")
                                .HasColumnName("playback_device_id");

                            b1.Property<string>("RecordingDeviceId")
                                .HasColumnType("text")
                                .HasColumnName("recording_device_id");

                            b1.Property<string>("WebcamDeviceId")
                                .HasColumnType("text")
                                .HasColumnName("webcam_device_id");

                            b1.HasKey("UserProfileId");

                            b1.ToTable("user_profiles", "users");

                            b1.WithOwner()
                                .HasForeignKey("UserProfileId");
                        });

                    b.Navigation("Account")
                        .IsRequired();

                    b.Navigation("Privacy")
                        .IsRequired();

                    b.Navigation("SoundVideo")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
