// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using UserService.Api.Infrastructure.Persistence;

#nullable disable

namespace UserService.Api.Migrations
{
    [DbContext(typeof(UserDbContext))]
    partial class UserDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("users")
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("UserService.Api.Domain.UserProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.ToTable("user_profiles", "users");
                });

            modelBuilder.Entity("UserService.Api.Domain.UserProfile", b =>
                {
                    b.OwnsOne("UserService.Api.Domain.ValueObjects.AccountSettings", "Account", b1 =>
                        {
                            b1.Property<Guid>("UserProfileId")
                                .HasColumnType("uuid");

                            b1.Property<string>("AboutMe")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("about_me");

                            b1.Property<string>("AvatarUrl")
                                .HasColumnType("text")
                                .HasColumnName("avatar_url");

                            b1.HasKey("UserProfileId");

                            b1.ToTable("user_profiles", "users");

                            b1.WithOwner()
                                .HasForeignKey("UserProfileId");
                        });

                    b.OwnsOne("UserService.Api.Domain.ValueObjects.NotificationSettings", "Notifications", b1 =>
                        {
                            b1.Property<Guid>("UserProfileId")
                                .HasColumnType("uuid");

                            b1.Property<bool>("DisciplineChatMessages")
                                .HasColumnType("boolean")
                                .HasColumnName("notify_discipline_chats");

                            b1.Property<bool>("Mentions")
                                .HasColumnType("boolean")
                                .HasColumnName("notify_mentions");

                            b1.Property<bool>("NewMessages")
                                .HasColumnType("boolean")
                                .HasColumnName("notify_new_messages");

                            b1.Property<bool>("NotificationSound")
                                .HasColumnType("boolean")
                                .HasColumnName("notify_sound");

                            b1.HasKey("UserProfileId");

                            b1.ToTable("user_profiles", "users");

                            b1.WithOwner()
                                .HasForeignKey("UserProfileId");
                        });

                    b.OwnsOne("UserService.Api.Domain.ValueObjects.PrivacySettings", "Privacy", b1 =>
                        {
                            b1.Property<Guid>("UserProfileId")
                                .HasColumnType("uuid");

                            b1.Property<bool>("ShowLastVisitTime")
                                .HasColumnType("boolean")
                                .HasColumnName("show_last_visit_time");

                            b1.Property<bool>("ShowOnlineStatus")
                                .HasColumnType("boolean")
                                .HasColumnName("show_online_status");

                            b1.HasKey("UserProfileId");

                            b1.ToTable("user_profiles", "users");

                            b1.WithOwner()
                                .HasForeignKey("UserProfileId");
                        });

                    b.OwnsOne("UserService.Api.Domain.ValueObjects.SoundVideoSettings", "SoundVideo", b1 =>
                        {
                            b1.Property<Guid>("UserProfileId")
                                .HasColumnType("uuid");

                            b1.Property<string>("PlaybackDeviceId")
                                .HasColumnType("text")
                                .HasColumnName("playback_device_id");

                            b1.Property<string>("RecordingDeviceId")
                                .HasColumnType("text")
                                .HasColumnName("recording_device_id");

                            b1.Property<string>("WebcamDeviceId")
                                .HasColumnType("text")
                                .HasColumnName("webcam_device_id");

                            b1.HasKey("UserProfileId");

                            b1.ToTable("user_profiles", "users");

                            b1.WithOwner()
                                .HasForeignKey("UserProfileId");
                        });

                    b.Navigation("Account")
                        .IsRequired();

                    b.Navigation("Notifications")
                        .IsRequired();

                    b.Navigation("Privacy")
                        .IsRequired();

                    b.Navigation("SoundVideo")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
