import { cssInterop } from "nativewind";
import type { ComponentType } from "react";
import * as Phosphor from "phosphor-react-native";
import type { IconProps } from "./phosphor-types";

export type { IconProps } from "./phosphor-types";

const iconInterop = {
  className: {
    target: "style" as const,
    nativeStyleToProp: {
      color: true as const,
    },
  },
} as const;

const wrap = (Base: Parameters<typeof cssInterop>[0]) =>
  cssInterop(Base, iconInterop as never) as ComponentType<IconProps>;

const iconBases = {
  ArrowBendUpLeftIcon: Phosphor.ArrowBendUpLeftIcon,
  ArrowBendDoubleUpRightIcon: Phosphor.ArrowBendDoubleUpRightIcon,
  AtIcon: Phosphor.AtIcon,
  BellIcon: Phosphor.BellIcon,
  BellSlashIcon: Phosphor.BellSlashIcon,
  BookOpenIcon: Phosphor.BookOpenIcon,
  CaretDownIcon: Phosphor.CaretDownIcon,
  CaretLeftIcon: Phosphor.CaretLeftIcon,
  CaretRightIcon: Phosphor.CaretRightIcon,
  ChatCircleTextIcon: Phosphor.ChatCircleTextIcon,
  ChatsCircleIcon: Phosphor.ChatsCircleIcon,
  CheckIcon: Phosphor.CheckIcon,
  ChecksIcon: Phosphor.ChecksIcon,
  ClockIcon: Phosphor.ClockIcon,
  CopyIcon: Phosphor.CopyIcon,
  DeviceMobileIcon: Phosphor.DeviceMobileIcon,
  DotsThreeVerticalIcon: Phosphor.DotsThreeVerticalIcon,
  EnvelopeIcon: Phosphor.EnvelopeIcon,
  EnvelopeSimpleIcon: Phosphor.EnvelopeSimpleIcon,
  FileIcon: Phosphor.FileIcon,
  FunnelIcon: Phosphor.FunnelIcon,
  GearIcon: Phosphor.GearIcon,
  InfoIcon: Phosphor.InfoIcon,
  ImageSquareIcon: Phosphor.ImageSquareIcon,
  LaptopIcon: Phosphor.LaptopIcon,
  LockIcon: Phosphor.LockIcon,
  MagnifyingGlassIcon: Phosphor.MagnifyingGlassIcon,
  MicrophoneIcon: Phosphor.MicrophoneIcon,
  MicrophoneSlashIcon: Phosphor.MicrophoneSlashIcon,
  MonitorIcon: Phosphor.MonitorIcon,
  MonitorArrowUpIcon: Phosphor.MonitorArrowUpIcon,
  PaperPlaneRightIcon: Phosphor.PaperPlaneRightIcon,
  PencilSimpleIcon: Phosphor.PencilSimpleIcon,
  PhoneDisconnectIcon: Phosphor.PhoneDisconnectIcon,
  PhoneIcon: Phosphor.PhoneIcon,
  PlusCircleIcon: Phosphor.PlusCircleIcon,
  PlusIcon: Phosphor.PlusIcon,
  ProhibitIcon: Phosphor.ProhibitIcon,
  PushPinIcon: Phosphor.PushPinIcon,
  PushPinSlashIcon: Phosphor.PushPinSlashIcon,
  ShieldCheckIcon: Phosphor.ShieldCheckIcon,
  SignOutIcon: Phosphor.SignOutIcon,
  SmileyIcon: Phosphor.SmileyIcon,
  SpeakerHighIcon: Phosphor.SpeakerHighIcon,
  ScreencastIcon: Phosphor.ScreencastIcon,
  TrashIcon: Phosphor.TrashIcon,
  UploadSimpleIcon: Phosphor.UploadSimpleIcon,
  UserCircleIcon: Phosphor.UserCircleIcon,
  UserIcon: Phosphor.UserIcon,
  UsersIcon: Phosphor.UsersIcon,
  VideoCameraIcon: Phosphor.VideoCameraIcon,
  WarningCircleIcon: Phosphor.WarningCircleIcon,
  XIcon: Phosphor.XIcon,
} as const;

const wrappedIcons = Object.fromEntries(
  (Object.entries(iconBases) as [keyof typeof iconBases, (typeof iconBases)[keyof typeof iconBases]][]).map(
    ([name, Base]) => [name, wrap(Base)],
  ),
) as { [K in keyof typeof iconBases]: ComponentType<IconProps> };

export const {
  ArrowBendUpLeftIcon,
  ArrowBendDoubleUpRightIcon,
  AtIcon,
  BellIcon,
  BellSlashIcon,
  BookOpenIcon,
  CaretDownIcon,
  CaretLeftIcon,
  CaretRightIcon,
  ChatCircleTextIcon,
  ChatsCircleIcon,
  CheckIcon,
  ChecksIcon,
  ClockIcon,
  CopyIcon,
  DeviceMobileIcon,
  DotsThreeVerticalIcon,
  EnvelopeIcon,
  EnvelopeSimpleIcon,
  FileIcon,
  FunnelIcon,
  GearIcon,
  InfoIcon,
  ImageSquareIcon,
  LaptopIcon,
  LockIcon,
  MagnifyingGlassIcon,
  MicrophoneIcon,
  MicrophoneSlashIcon,
  MonitorIcon,
  MonitorArrowUpIcon,
  PaperPlaneRightIcon,
  PencilSimpleIcon,
  PhoneDisconnectIcon,
  PhoneIcon,
  PlusCircleIcon,
  PlusIcon,
  ProhibitIcon,
  PushPinIcon,
  PushPinSlashIcon,
  ShieldCheckIcon,
  SignOutIcon,
  SmileyIcon,
  SpeakerHighIcon,
  ScreencastIcon,
  TrashIcon,
  UploadSimpleIcon,
  UserCircleIcon,
  UserIcon,
  UsersIcon,
  VideoCameraIcon,
  WarningCircleIcon,
  XIcon,
} = wrappedIcons;
