server {
  listen 8080;
  server_name _;
  root /usr/share/nginx/html;
  index index.html;

  gzip on;
  gzip_static on;
  gzip_types text/plain text/css application/javascript application/json image/svg+xml;
  gzip_min_length 1024;
  gzip_comp_level 6;
  gzip_vary on;

  location = /health/live {
    access_log off;
    add_header Content-Type text/plain;
    return 200 "ok";
  }

  location = /health/ready {
    access_log off;
    add_header Content-Type text/plain;
    return 200 "ok";
  }

  location / {
    try_files $uri $uri/ /index.html;
  }
}
