apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: linkerd-viz
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: urfu-link
  source:
    repoURL: https://helm.linkerd.io/edge
    targetRevision: 2026.3.2
    chart: linkerd-viz
    helm:
      parameters:
        - name: dashboard.enforcedHostRegexp
          value: ".*"
  destination:
    server: https://kubernetes.default.svc
    namespace: linkerd-viz
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
