apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  project: urfu-link
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 58.2.1
    chart: kube-prometheus-stack
    helm:
      releaseName: kube-prometheus-stack
      parameters:
        - name: grafana.admin.existingSecret
          value: grafana-admin
        - name: grafana.admin.passwordKey
          value: admin-password
        - name: prometheus.prometheusSpec.remoteWriteReceiver.enabled
          value: "true"
        - name: prometheus-node-exporter.enabled
          value: "false"
        - name: prometheus.prometheusSpec.retention
          value: 3d
        - name: prometheus.prometheusSpec.resources.requests.cpu
          value: 100m
        - name: prometheus.prometheusSpec.resources.requests.memory
          value: 512Mi
        - name: prometheus.prometheusSpec.resources.limits.memory
          value: 1Gi
        - name: grafana.resources.requests.cpu
          value: 50m
        - name: grafana.resources.requests.memory
          value: 128Mi
        - name: grafana.resources.limits.memory
          value: 256Mi
        - name: alertmanager.enabled
          value: "false"
        - name: grafana.envFromSecret
          value: grafana-oidc
        - name: grafana.grafana\.ini.server.root_url
          value: https://grafana.ghjc.ru
        - name: grafana.grafana\.ini.auth\.generic_oauth.enabled
          value: "true"
        - name: grafana.grafana\.ini.auth\.generic_oauth.name
          value: Keycloak
        - name: grafana.grafana\.ini.auth\.generic_oauth.allow_sign_up
          value: "true"
        - name: grafana.grafana\.ini.auth\.generic_oauth.scopes
          value: openid profile email roles
        - name: grafana.grafana\.ini.auth\.generic_oauth.auth_url
          value: https://id.ghjc.ru/realms/urfu-link/protocol/openid-connect/auth
        - name: grafana.grafana\.ini.auth\.generic_oauth.token_url
          value: https://id.ghjc.ru/realms/urfu-link/protocol/openid-connect/token
        - name: grafana.grafana\.ini.auth\.generic_oauth.api_url
          value: https://id.ghjc.ru/realms/urfu-link/protocol/openid-connect/userinfo
        - name: grafana.grafana\.ini.auth\.generic_oauth.role_attribute_path
          value: "contains(groups[*], 'admin') && 'Admin' || ''"
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
