apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-stateful
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "7"
spec:
  project: urfu-link
  source:
    repoURL: https://github.com/ConquestSucks/urfu-link.git
    targetRevision: master
    path: deploy/k8s/platform/stateful
  ignoreDifferences:
    - kind: Secret
      name: urfu-postgres-superuser
      namespace: urfu-platform
      jsonPointers:
        - /data/password
        - /stringData
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - RespectIgnoreDifferences=true
    retry:
      limit: 20
      backoff:
        duration: 30s
        factor: 2
        maxDuration: 20m
