apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  project: urfu-link
  source:
    repoURL: https://helm.releases.hashicorp.com
    targetRevision: 0.32.0
    chart: vault
    helm:
      releaseName: vault
      parameters:
        - name: server.standalone.enabled
          value: "true"
        - name: server.standalone.config
          value: |
            ui = true
            listener "tcp" {
              tls_disable = 1
              address = "[::]:8200"
              cluster_address = "[::]:8201"
            }
            storage "file" {
              path = "/vault/data"
            }
  destination:
    server: https://kubernetes.default.svc
    namespace: vault
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
