nameOverride: media-service
fullnameOverride: media-service
image:
  repository: urfu-link/media-service
  pullPolicy: IfNotPresent
  tag: dev-local

replicaCount: 1

service:
  grpc:
    enabled: true

env:
  ASPNETCORE_ENVIRONMENT: Development
  ASPNETCORE_URLS: http://+:8080
  Storage__Endpoint: http://minio.urfu-platform.svc.cluster.local:9000
  Storage__PublicEndpoint: http://storage.dev.127.0.0.1.nip.io
  Storage__PrivateBucket: media-private
  Storage__PublicBucket: media-public

secrets:
  enabled: true
  name: media-service-secrets

rollout:
  enabled: false
  autoPromotionEnabled: true

autoscaling:
  enabled: false

serviceMonitor:
  enabled: false

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 256Mi

migrations:
  enabled: true
  command: ["dotnet", "MediaService.Api.dll", "--migrate"]

