deploymentMode: SingleBinary

gateway:
  enabled: false

lokiCanary:
  enabled: false

test:
  enabled: false

loki:
  auth_enabled: false
  commonConfig:
    replication_factor: 1
  storage:
    type: filesystem
  schemaConfig:
    configs:
      - from: "2024-04-01"
        store: tsdb
        object_store: filesystem
        schema: v13
        index:
          prefix: loki_index_
          period: 24h
  limits_config:
    allow_structured_metadata: true
    volume_enabled: true

singleBinary:
  replicas: 1
  affinity: {}

backend:
  replicas: 0
  affinity: {}

read:
  replicas: 0
  affinity: {}

write:
  replicas: 0
  affinity: {}

ingester:
  replicas: 0
  affinity: {}

querier:
  replicas: 0
  affinity: {}

queryFrontend:
  replicas: 0
  affinity: {}

queryScheduler:
  replicas: 0
  affinity: {}

distributor:
  replicas: 0
  affinity: {}

compactor:
  replicas: 0
  affinity: {}

indexGateway:
  replicas: 0
  affinity: {}

bloomCompactor:
  replicas: 0
  affinity: {}

bloomGateway:
  replicas: 0
  affinity: {}
