{{- if and .Values.migrations.enabled .Values.migrations.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "urfu-service.migrationsServiceAccountName" . }}
  labels:
    app.kubernetes.io/name: {{ include "urfu-service.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: migrations
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-10"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
    {{- with .Values.migrations.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
automountServiceAccountToken: {{ .Values.migrations.serviceAccount.automountServiceAccountToken }}
{{- end }}
