namespace Urfu.Link.Services.Notification.Domain.Enums;

public enum NotificationCategory
{
    ChatMessageDirect = 1,
    ChatMessageMention = 2,
    ChatMessageDiscipline = 3,
    ChatThreadReply = 4,
    ChatReplyToMe = 5,
    ChatReaction = 6,
    ChatMessagePinned = 7,
    ChatParticipantChanged = 8,
    CallIncoming = 10,
    CallMissed = 11,
    DisciplineAnnouncement = 20,
    DisciplineMaterial = 21,
    DisciplineDeadline = 22,
    DisciplineEnrollment = 23,
    DisciplineUnenrollment = 24,
    DisciplineUpdated = 25,
    DisciplineDeleted = 26,
    SystemMaintenance = 30,
    SystemUpdate = 31,
    AdminChatInvite = 40,
    AdminRoleChanged = 41,
    MediaAccessGranted = 50,
    MediaAccessRevoked = 51,
    MediaUploadProcessed = 52,
    MediaAssetDeleted = 53,
}
