apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-web-oauth2-proxy-alpha-config
  namespace: urfu-prod
data:
  alpha-config.yaml: |
    injectRequestHeaders:
      - name: Authorization
        values:
          - claim: access_token
            prefix: "Bearer "
