apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-oidc
  namespace: observability
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: grafana-oidc
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        GF_AUTH_GENERIC_OAUTH_CLIENT_ID: '{{ .client_id }}'
        GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: '{{ .client_secret }}'
  data:
    - secretKey: client_id
      remoteRef:
        key: urfu-link/prod/grafana-oidc
        property: client_id
    - secretKey: client_secret
      remoteRef:
        key: urfu-link/prod/grafana-oidc
        property: client_secret
