apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: headlamp-oidc
  namespace: urfu-platform
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: headlamp-oidc
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        OIDC_CLIENT_ID: '{{ .client_id }}'
        OIDC_CLIENT_SECRET: '{{ .client_secret }}'
        OIDC_ISSUER_URL: '{{ .issuer_url }}'
        OIDC_SCOPES: '{{ .scopes }}'
        OIDC_USE_PKCE: '{{ .use_pkce }}'
  data:
    - secretKey: client_id
      remoteRef:
        key: urfu-link/prod/headlamp
        property: client_id
    - secretKey: client_secret
      remoteRef:
        key: urfu-link/prod/headlamp
        property: client_secret
    - secretKey: issuer_url
      remoteRef:
        key: urfu-link/prod/headlamp
        property: issuer_url
    - secretKey: scopes
      remoteRef:
        key: urfu-link/prod/headlamp
        property: scopes
    - secretKey: use_pkce
      remoteRef:
        key: urfu-link/prod/headlamp
        property: use_pkce
