apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keycloak-secrets
  namespace: urfu-platform
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: keycloak-secrets
  data:
    - secretKey: admin_username
      remoteRef:
        key: urfu-link/prod/keycloak
        property: admin_username
    - secretKey: admin_password
      remoteRef:
        key: urfu-link/prod/keycloak
        property: admin_password
    - secretKey: db_host
      remoteRef:
        key: urfu-link/prod/keycloak
        property: db_host
    - secretKey: db_name
      remoteRef:
        key: urfu-link/prod/keycloak
        property: db_name
    - secretKey: db_username
      remoteRef:
        key: urfu-link/prod/keycloak
        property: db_username
    - secretKey: db_password
      remoteRef:
        key: urfu-link/prod/keycloak
        property: db_password
