apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: linkerd-viz-oauth2
  namespace: linkerd-viz
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: linkerd-viz-oauth2
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        client-id: '{{ .client_id }}'
        client-secret: '{{ .client_secret }}'
        cookie-secret: '{{ .cookie_secret }}'
  data:
    - secretKey: client_id
      remoteRef:
        key: urfu-link/prod/linkerd-viz
        property: client_id
    - secretKey: client_secret
      remoteRef:
        key: urfu-link/prod/linkerd-viz
        property: client_secret
    - secretKey: cookie_secret
      remoteRef:
        key: urfu-link/prod/linkerd-viz
        property: cookie_secret
