apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: minio-oidc
  namespace: urfu-platform
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: minio-oidc
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        MINIO_IDENTITY_OPENID_CLIENT_ID: '{{ .client_id }}'
        MINIO_IDENTITY_OPENID_CLIENT_SECRET: '{{ .client_secret }}'
  data:
    - secretKey: client_id
      remoteRef:
        key: urfu-link/prod/minio-oidc
        property: client_id
    - secretKey: client_secret
      remoteRef:
        key: urfu-link/prod/minio-oidc
        property: client_secret
