apiVersion: v1
kind: ConfigMap
metadata:
  name: pomerium-config
  namespace: urfu-platform
data:
  config.yaml: |
    authenticate_service_url: https://auth.ghjc.ru

    idp_provider: oidc
    idp_provider_url: https://id.ghjc.ru/realms/urfu-link
    idp_scopes:
      - openid
      - email
      - profile
      - roles

    cookie_domain: .ghjc.ru
    cookie_secure: true
    cookie_http_only: true
    cookie_same_site: lax
    cookie_name: _pomerium
    cookie_expire: 1h

    databroker_storage_type: redis
    databroker_storage_connection_string: redis://urfu-redis.urfu-platform.svc.cluster.local:6379

    code_challenge_method: S256
    log_level: info

    routes:
      # Frontend — any authenticated user
      - from: https://urfu-link.ghjc.ru
        to: http://frontend-web.urfu-prod.svc.cluster.local:8080
        policy:
          - allow:
              or:
                - authenticated_user: true

      # Frontend API — inject Bearer token for YARP API Gateway
      - from: https://urfu-link.ghjc.ru
        to: http://api-gateway.urfu-prod.svc.cluster.local:8080
        prefix: /api
        policy:
          - allow:
              or:
                - authenticated_user: true
        set_request_headers:
          Authorization: "Bearer ${pomerium.access_token}"

      # Linkerd Viz — admin group only
      - from: https://linkerd.ghjc.ru
        to: http://web.linkerd-viz.svc.cluster.local:8084
        policy:
          - allow:
              and:
                - authenticated_user: true
                - groups:
                    has: admin
