apiVersion: v1
kind: ConfigMap
metadata:
  name: pomerium-config
  namespace: urfu-platform
data:
  config.yaml: |
    routes:
      # Frontend API — Pomerium passes identity JWT to upstream
      - from: https://urfu-link.ghjc.ru
        to: http://echo-test.urfu-prod.svc.cluster.local:8080
        prefix: /api
        policy:
          - allow:
              or:
                - authenticated_user: true
        pass_identity_headers: true

      # Frontend — any authenticated user
      - from: https://urfu-link.ghjc.ru
        to: http://frontend-web.urfu-prod.svc.cluster.local:8080
        policy:
          - allow:
              or:
                - authenticated_user: true

      # Linkerd Viz — admin group only
      - from: https://linkerd.ghjc.ru
        to: http://web.linkerd-viz.svc.cluster.local:8084
        policy:
          - allow:
              and:
                - authenticated_user: true
                - groups:
                    has: admin
