apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vault-oidc
  namespace: vault
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: vault-oidc
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        client_id: '{{ .client_id }}'
        client_secret: '{{ .client_secret }}'
  data:
    - secretKey: client_id
      remoteRef:
        key: urfu-link/prod/vault-oidc
        property: client_id
    - secretKey: client_secret
      remoteRef:
        key: urfu-link/prod/vault-oidc
        property: client_secret
