nameOverride: frontend-web
fullnameOverride: frontend-web
image:
  repository: ghcr.io/conquestsucks/urfu-link/frontend-web
  pullPolicy: IfNotPresent
  tag: sha-882644a

imagePullSecrets:
  - name: ghcr-pull-secret

replicaCount: 1

podAnnotations:
  linkerd.io/inject: disabled

securityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: false
  capabilities:
    drop:
      - ALL

service:
  port: 8080

env:
  APP_ENV: prod
  EXPO_PUBLIC_API_URL: https://api.urfu-link.ghjc.ru

rollout:
  enabled: true
  autoPromotionEnabled: true

autoscaling:
  enabled: false

serviceMonitor:
  enabled: false

resources:
  requests:
    cpu: 25m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 256Mi

networkPolicy:
  allowToSameNamespace: false
  allowedIngressNamespaces:
    - ingress-nginx
  allowedEgressNamespaces: []

probes:
  livenessPath: /health/live
  readinessPath: /health/ready
  startupPath: /health/live
