nameOverride: user-service
fullnameOverride: user-service
image:
  repository: ghcr.io/conquestsucks/urfu-link/user-service
  pullPolicy: IfNotPresent
  tag: sha-24bdc9c

imagePullSecrets:
  - name: ghcr-pull-secret

replicaCount: 1

env:
  ASPNETCORE_ENVIRONMENT: Production
  ASPNETCORE_URLS: http://+:8080
  Observability__Otlp__Endpoint: http://otel-collector.observability.svc.cluster.local:4317
  Kafka__BootstrapServers: urfu-kafka.urfu-platform.svc.cluster.local:9092
  Auth__Authority: http://keycloak.urfu-platform.svc.cluster.local:8080/realms/urfu-link
  Infrastructure__Redis__Configuration: urfu-redis.urfu-platform.svc.cluster.local:6379

secrets:
  enabled: true
  name: user-service-secrets

rollout:
  enabled: true
  autoPromotionEnabled: false

autoscaling:
  enabled: false

serviceMonitor:
  enabled: true

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi
