apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: headlamp
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  project: urfu-link
  source:
    repoURL: https://kubernetes-sigs.github.io/headlamp/
    targetRevision: 0.25.0
    chart: headlamp
    helm:
      releaseName: headlamp
      valueFiles:
        - $values/deploy/helm/services/headlamp/values-prod.yaml
  sources:
    - repoURL: https://kubernetes-sigs.github.io/headlamp/
      targetRevision: 0.25.0
      chart: headlamp
    - repoURL: https://github.com/ConquestSucks/urfu-link.git
      targetRevision: master
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: urfu-platform
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
