nameOverride: notification-service
fullnameOverride: notification-service
image:
  repository: urfu-link/notification-service
  pullPolicy: IfNotPresent
  tag: dev-local

replicaCount: 1

service:
  grpc:
    enabled: true

env:
  ASPNETCORE_ENVIRONMENT: Development
  ASPNETCORE_URLS: http://+:8080
  UserService__GrpcEndpoint: http://user-service:8081
  PresenceService__GrpcEndpoint: http://presence-service:8081

secrets:
  enabled: true
  name: notification-service-secrets

rollout:
  enabled: false
  autoPromotionEnabled: true

autoscaling:
  enabled: false

serviceMonitor:
  enabled: false

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 256Mi

migrations:
  enabled: true
  command: ["dotnet", "NotificationService.Api.dll", "--migrate"]

