nameOverride: call-service
fullnameOverride: call-service
image:
  repository: urfu-link/call-service
  pullPolicy: IfNotPresent
  tag: dev-local

replicaCount: 1

service:
  grpc:
    enabled: true

env:
  ASPNETCORE_ENVIRONMENT: Development
  ASPNETCORE_URLS: http://+:8080
  GrpcClients__InternalAuth__TokenEndpoint: http://keycloak.urfu-platform.svc.cluster.local:8080/realms/urfu-link/protocol/openid-connect/token
  GrpcClients__InternalAuth__ClientId: chat-service-internal
  GrpcClients__InternalAuth__ClientSecret: chat-service-internal-dev-secret
  GrpcClients__ChatService__Address: http://chat-service:8081

secrets:
  enabled: true
  name: call-service-secrets

rollout:
  enabled: false
  autoPromotionEnabled: true

autoscaling:
  enabled: false

serviceMonitor:
  enabled: false

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 256Mi

