apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../stateful

patchesStrategicMerge:
  - patch-postgres.yaml
  - patch-mongodb.yaml
  - patch-redis.yaml
  - patch-minio.yaml
  - patch-kafka-broker.yaml
  - patch-kafka-controller.yaml
