apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../stateful

patches:
  - path: patch-postgres.yaml
  - path: patch-mongodb.yaml
  - path: patch-redis.yaml
  - path: patch-minio.yaml
  - path: patch-kafka-cluster.yaml
  - path: patch-kafka-broker.yaml
  - path: patch-kafka-controller.yaml
  - path: patch-kafka-topics.yaml
