apiVersion: minio.min.io/v2
kind: Tenant
metadata:
  name: urfu-minio
  namespace: urfu-platform
spec:
  pools:
    - name: pool-0
      servers: 4
      volumesPerServer: 4
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 4Gi
          storageClassName: fast-ssd
