apiVersion: kafka.strimzi.io/v1
kind: KafkaTopic
metadata:
  name: urfu-user-events-v1
  namespace: urfu-platform
spec:
  replicas: 1
---
apiVersion: kafka.strimzi.io/v1
kind: KafkaTopic
metadata:
  name: urfu-media-events-v1
  namespace: urfu-platform
spec:
  replicas: 1
---
apiVersion: kafka.strimzi.io/v1
kind: KafkaTopic
metadata:
  name: urfu-chat-events-v1
  namespace: urfu-platform
spec:
  replicas: 1
---
apiVersion: kafka.strimzi.io/v1
kind: KafkaTopic
metadata:
  name: urfu-presence-events-v1
  namespace: urfu-platform
spec:
  replicas: 1
---
apiVersion: kafka.strimzi.io/v1
kind: KafkaTopic
metadata:
  name: urfu-notification-events-v1
  namespace: urfu-platform
spec:
  replicas: 1
---
apiVersion: kafka.strimzi.io/v1
kind: KafkaTopic
metadata:
  name: urfu-call-events-v1
  namespace: urfu-platform
spec:
  replicas: 1
---
apiVersion: kafka.strimzi.io/v1
kind: KafkaTopic
metadata:
  name: urfu-call-events-v1-dlq
  namespace: urfu-platform
spec:
  replicas: 1
