apiVersion: redis.redis.opstreelabs.in/v1beta2
kind: RedisCluster
metadata:
  name: urfu-redis
  namespace: urfu-platform
spec:
  storage:
    volumeClaimTemplate:
      spec:
        resources:
          requests:
            storage: 4Gi
