apiVersion: v1
kind: Secret
metadata:
  name: api-gateway-secrets
  namespace: urfu-dev
type: Opaque
stringData:
  Auth__Authority: http://keycloak.urfu-platform.svc.cluster.local:8080/realms/urfu-link
  Observability__Otlp__Endpoint: http://otel-collector.observability.svc.cluster.local:4317
---
apiVersion: v1
kind: Secret
metadata:
  name: user-service-secrets
  namespace: urfu-dev
type: Opaque
stringData:
  ConnectionStrings__Primary: Host=postgres.urfu-platform.svc.cluster.local;Port=5432;Database=user_db;Username=user;Password=user
  Kafka__BootstrapServers: kafka.urfu-platform.svc.cluster.local:9092
  Auth__Authority: http://keycloak.urfu-platform.svc.cluster.local:8080/realms/urfu-link
  Observability__Otlp__Endpoint: http://otel-collector.observability.svc.cluster.local:4317
  Infrastructure__Redis__Configuration: redis.urfu-platform.svc.cluster.local:6379
---
apiVersion: v1
kind: Secret
metadata:
  name: media-service-secrets
  namespace: urfu-dev
type: Opaque
stringData:
  ConnectionStrings__Primary: Host=postgres.urfu-platform.svc.cluster.local;Port=5432;Database=media_db;Username=media;Password=media
  Kafka__BootstrapServers: kafka.urfu-platform.svc.cluster.local:9092
  Auth__Authority: http://keycloak.urfu-platform.svc.cluster.local:8080/realms/urfu-link
  Observability__Otlp__Endpoint: http://otel-collector.observability.svc.cluster.local:4317
  Infrastructure__Redis__Configuration: redis.urfu-platform.svc.cluster.local:6379
---
apiVersion: v1
kind: Secret
metadata:
  name: chat-service-secrets
  namespace: urfu-dev
type: Opaque
stringData:
  ConnectionStrings__Primary: mongodb://mongo.urfu-platform.svc.cluster.local:27017/chat_db
  Kafka__BootstrapServers: kafka.urfu-platform.svc.cluster.local:9092
  Auth__Authority: http://keycloak.urfu-platform.svc.cluster.local:8080/realms/urfu-link
  Observability__Otlp__Endpoint: http://otel-collector.observability.svc.cluster.local:4317
  Infrastructure__Redis__Configuration: redis.urfu-platform.svc.cluster.local:6379
---
apiVersion: v1
kind: Secret
metadata:
  name: presence-service-secrets
  namespace: urfu-dev
type: Opaque
stringData:
  ConnectionStrings__Primary: redis.urfu-platform.svc.cluster.local:6379
  Kafka__BootstrapServers: kafka.urfu-platform.svc.cluster.local:9092
  Auth__Authority: http://keycloak.urfu-platform.svc.cluster.local:8080/realms/urfu-link
  Observability__Otlp__Endpoint: http://otel-collector.observability.svc.cluster.local:4317
  Infrastructure__Redis__Configuration: redis.urfu-platform.svc.cluster.local:6379
---
apiVersion: v1
kind: Secret
metadata:
  name: notification-service-secrets
  namespace: urfu-dev
type: Opaque
stringData:
  Kafka__BootstrapServers: kafka.urfu-platform.svc.cluster.local:9092
  Auth__Authority: http://keycloak.urfu-platform.svc.cluster.local:8080/realms/urfu-link
  Observability__Otlp__Endpoint: http://otel-collector.observability.svc.cluster.local:4317
  Infrastructure__Redis__Configuration: redis.urfu-platform.svc.cluster.local:6379
---
apiVersion: v1
kind: Secret
metadata:
  name: call-service-secrets
  namespace: urfu-dev
type: Opaque
stringData:
  Kafka__BootstrapServers: kafka.urfu-platform.svc.cluster.local:9092
  Auth__Authority: http://keycloak.urfu-platform.svc.cluster.local:8080/realms/urfu-link
  Observability__Otlp__Endpoint: http://otel-collector.observability.svc.cluster.local:4317
  Infrastructure__Redis__Configuration: redis.urfu-platform.svc.cluster.local:6379
