nameOverride: chat-service
fullnameOverride: chat-service
image:
  repository: ghcr.io/conquestsucks/urfu-link/chat-service
  pullPolicy: IfNotPresent
  tag: sha-cac96a8

imagePullSecrets:
  - name: ghcr-pull-secret

replicaCount: 1

env:
  ASPNETCORE_ENVIRONMENT: Production
  ASPNETCORE_URLS: http://+:8080
  Observability__Otlp__Endpoint: http://otel-collector.observability.svc.cluster.local:4317
  Kafka__BootstrapServers: urfu-kafka.urfu-platform.svc.cluster.local:9092
  Auth__TokenHeader: X-Pomerium-Jwt-Assertion
  Auth__JwksUrl: http://pomerium.urfu-platform.svc.cluster.local/.well-known/pomerium/jwks.json
  Auth__Audience: urfu-link.ghjc.ru
  Auth__ValidIssuer: urfu-link.ghjc.ru
  Auth__NameClaim: email
  Auth__RoleClaim: groups
  Infrastructure__Redis__Configuration: urfu-redis.urfu-platform.svc.cluster.local:6379

secrets:
  enabled: true
  name: chat-service-secrets

rollout:
  enabled: true
  autoPromotionEnabled: true

autoscaling:
  enabled: false

serviceMonitor:
  enabled: true

resources:
  requests:
    cpu: 25m
    memory: 64Mi
  limits:
    cpu: 250m
    memory: 256Mi
