apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespaces.yaml
  - cert-manager/cluster-issuer.yaml
  - ingress/api-gateway-ingress.yaml
  - ingress/frontend-web-ingress.yaml
  - network/deny-all-default.yaml
  - network/service-egress-policies.yaml
  - argocd/project.yaml
  - argocd/applicationset.yaml
  - external-secrets/cluster-secret-store.yaml
  - external-secrets/api-gateway-external-secret.yaml
  - external-secrets/services-external-secrets.yaml
  - external-secrets/minio-bootstrap-external-secret.yaml
  - identity/keycloak-external-secret.yaml
  - identity/headlamp-external-secret.yaml
  - identity/keycloak.yaml
  - media/livekit.yaml
  - media/coturn.yaml
  - observability/otel-collector-config.yaml
  - observability/otel-collector.yaml
  - linkerd/server-authentication.yaml
