nameOverride: api-gateway
fullnameOverride: api-gateway
image:
  repository: ghcr.io/conquestsucks/urfu-link/api-gateway
  pullPolicy: IfNotPresent
  tag: sha-7dfb27f

imagePullSecrets:
  - name: ghcr-pull-secret

replicaCount: 1

env:
  ASPNETCORE_ENVIRONMENT: Production
  ASPNETCORE_URLS: http://+:8080
  Observability__Otlp__Endpoint: http://otel-collector.observability.svc.cluster.local:4317
  Auth__Authority: http://keycloak.urfu-platform.svc.cluster.local:8080/realms/urfu-link

secrets:
  enabled: true
  name: api-gateway-secrets

rollout:
  enabled: true
  autoPromotionEnabled: true

autoscaling:
  enabled: false

serviceMonitor:
  enabled: true

resources:
  requests:
    cpu: 25m
    memory: 64Mi
  limits:
    cpu: 250m
    memory: 256Mi
