nameOverride: api-gateway
fullnameOverride: api-gateway
image:
  repository: ghcr.io/conquestsucks/urfu-link/api-gateway
  pullPolicy: IfNotPresent
  tag: sha-cac96a8

imagePullSecrets:
  - name: ghcr-pull-secret

replicaCount: 1

env:
  ASPNETCORE_ENVIRONMENT: Production
  ASPNETCORE_URLS: http://+:8080
  Observability__Otlp__Endpoint: http://otel-collector.observability.svc.cluster.local:4317
  Auth__TokenHeader: X-Pomerium-Jwt-Assertion
  Auth__JwksUrl: http://pomerium.urfu-platform.svc.cluster.local/.well-known/pomerium/jwks.json
  Auth__Audience: urfu-link.ghjc.ru
  Auth__ValidIssuer: urfu-link.ghjc.ru
  Auth__NameClaim: email
  Auth__RoleClaim: groups
  Cors__AllowedOrigins__0: https://urfu-link.ghjc.ru

secrets:
  enabled: true
  name: api-gateway-secrets

rollout:
  enabled: true
  autoPromotionEnabled: true

autoscaling:
  enabled: false

serviceMonitor:
  enabled: true

networkPolicy:
  allowedIngressNamespaces:
    - urfu-platform

resources:
  requests:
    cpu: 25m
    memory: 64Mi
  limits:
    cpu: 250m
    memory: 256Mi
